name: icp
description: icp is an iOS and Android app for connecting to decentralized social networks like Mastodon, Tusk and the Fediverse.

version: 2.0.0+35

environment:
  sdk: '^3.7.2'

dependencies:
  flutter:
    sdk: flutter

  lints: ^5.1.1
  dio: ^5.8.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_lint: ^2.6.5
  package_info_plus: ^8.3.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  flutter_web_browser: ^0.17.1
  app_links: ^6.4.0
  better_player: 
    path: ../better_player
  dio_http_cache:
    git:
      url: https://github.com/Ralf-Kraemer/dio-http-cache.git
  toot_ui: 
    path: ../toot_ui
  btox: 
    path: ../bTox
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  share_plus: ^10.1.4
  flutter_emoji: ^2.5.1

dev_dependencies:
  json_serializable: ^6.9.4
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo-icp.png
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-icp.png"